#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
. /lib/cryptsetup/functions

# Hooks for loading gnupg software and symmetrically encrypted key into
# the initramfs
crypttab_copy_keys_to_initramfs 'decrypt_gnupg' || exit 1

# Install gnupg software
copy_exec /usr/bin/gpg
